version: '3.1'

services:

  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 8081:2368
    networks:
       - backend
       - proxy
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db:3306
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      #url: http://localhost:8080
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: "Host:ghost.34.76.8.102.nip.io"
        traefik.docker.network: "proxy"

  db:
    image: mysql:5.7
    volumes:
       - /srv/nfs/mysql/data:/var/lib/mysql
    networks:
       - backend
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: ghost
       MYSQL_USER: ghost
       MYSQL_PASSWORD: ghost
  
networks:
    backend: 
      driver: overlay
    proxy: 
      external: true

